version: "3.8"

services:
    mongo-init:
        image: mongo:7.0
        container_name: mongo-init
        entrypoint: ["/bin/sh", "-c"]
        command: >
            "openssl rand -base64 756 > /data/configdb/mongo-keyfile &&
            chmod 400 /data/configdb/mongo-keyfile &&
            chown 999:999 /data/configdb/mongo-keyfile"
        volumes:
            - ./database/keyfile:/data/configdb
    mongo1:
        image: mongo:7.0
        command:
            [
                "--replSet",
                "${MONGO_REPLICA_SET}",
                "--bind_ip_all",
                "--port",
                "27021",
                "--auth",
                "--keyFile",
                "/data/configdb/mongo-keyfile"
            ]
        ports:
            - 27021:27021
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27021',priority:1},{_id:1,host:'host.docker.internal:27022',priority:0.5},{_id:2,host:'host.docker.internal:27023',priority:0.5}]}) }" | mongosh --port 27021 -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./database/data/mongo1_data:/data/db
            - ./database/configuration/mongo1_config:/data/configdb
            - ./database/keyfile:/data/configdb
        restart: unless-stopped
    mongo2:
        image: mongo:7.0
        command:
            [
                "--replSet",
                "${MONGO_REPLICA_SET}",
                "--bind_ip_all",
                "--port",
                "27022",
                "--auth",
                "--keyFile",
                "/data/configdb/mongo-keyfile"
            ]
        ports:
            - 27022:27022
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./database/data/mongo2_data:/data/db
            - ./database/configuration/mongo2_config:/data/configdb"
            - ./database/keyfile:/data/configdb
        restart: unless-stopped
    mongo3:
        image: mongo:7.0
        command:
            [
                "--replSet",
                "${MONGO_REPLICA_SET}",
                "--bind_ip_all",
                "--port",
                "27023",
                "--auth",
                "--keyFile",
                "/data/configdb/mongo-keyfile"
            ]
        ports:
            - 27023:27023
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./database/data/mongo3_data:/data/db
            - ./database/configuration/mongo3_config:/data/configdb
            - ./database/keyfile:/data/configdb
        restart: unless-stopped
