services:
    mongo:
        image: mongo:6.0
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./database/mongodb/data/mongo_data:/data/db
            - ./database/mongodb/config/mongo_config:/data/configdb
        restart: always
        ports:
            - 27017:27017

    redis:
        image: redis:7.2.4
        container_name: redis
        restart: always
        ports:
            - 6381:6381
        command: >
            redis-server --loadmodule /usr/lib/redis/modules/acl.so
            --aclfile /data/users.acl
        entrypoint: >
            sh -c "redis-server --daemonize yes &&
                    redis-cli ACL SETUSER ${REDIS_USERNAME} on '>${REDIS_PASSWORD}' allcommands allkeys &&
                    redis-cli ACL SETUSER default off &&
                    tail -f /dev/null"
        volumes:
            - ./database/redis/data:/data
    backend:
        container_name: backend
        depends_on:
            - redis
            - mongo
        restart: unless-stopped
        build:
            context: ../api
        ports:
            - 4000:4000
        volumes:
            - ../api/data:/app/data
