services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - backend
        restart: always
        volumes:
            - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ../client/dist/:/usr/share/nginx/html/
        ports:
            - 44380:44380
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    mongo:
        image: mongo:6.0
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./database/mongodb/data/mongo_data:/data/db
            - ./database/mongodb/config/mongo_config:/data/configdb
        restart: always
        ports:
            - 27017:27017
    redis:
        image: redis:7.2.4
        container_name: redis
        restart: always
        command: >
            redis-server --loadmodule /usr/lib/redis/modules/acl.so
            --aclfile /data/users.acl
        entrypoint: >
            sh -c "redis-server --daemonize yes &&
                    redis-cli ACL SETUSER ${REDIS_USERNAME} on '>${REDIS_PASSWORD}' allcommands allkeys &&
                    redis-cli ACL SETUSER default off &&
                    tail -f /dev/null"
        volumes:
            - ./database/redis/data:/data
        ports:
            - 6379:6379
    backend:
        container_name: backend
        depends_on:
            - redis
            - mongo
        restart: unless-stopped
        environment:
            NODE_ENV: PRO
            PRO_MONGODB_URI: mongodb://vutran0943:0943608225a@mongo:27017/KSTN_DB?authSource=admin
            PRO_REDIS_URI: redis://vutran0943:0943608225a@redis:6379
        build:
            context: ../api
        volumes:
            - ../api/data:/app/data
        ports:
            - 4000:4000
