@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21013482",
    "password": "1111"
}


### Register
POST {{url}}/api/register 
Content-Type: application/json

{
    "userId": "21013482",
    "firstName": "Trung",
    "lastName": "Trần Đức",
    "birthday": "2003-05-19",
    "cohort": 18,
    "faculty": "Công nghệ thông tin",
    "major": "kỹ thuật phần mềm",
    "password": "1111",
    "email": "tranducvu234@gmail.com",
    "phone": "0943608225",
    "gender": "nam",
    "levelYear": 1
}

### Get access token
GET {{url}}/api/access-token
