@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21013482",
    "password": "1111"
}


### Register
POST {{url}}/api/register 
Content-Type: application/json

{
    "userId": "21013481",
    "firstName": "Admin",
    "password": "1111",
    "groupCode": "004"
}

### Get access token
GET {{url}}/api/access-token
