@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21078101",
    "password": "1111"
}

### Create faculty
POST {{url}}/api/faculties
Content-Type: application/json

{
    "facultyName": "Dien tu",
    "managerIdList": ["670ce73281e90dfee50aa1cc"]
}

### Update faculty
PATCH {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf
Content-Type: application/json

{
   "data": {
        "facultyName": "2222a"
   }
}

### Delete faculty
DELETE {{url}}/api/faculties/67d9787d6f196d9d54ae3c86

### Get faculty by id
GET {{url}}/api/faculties/67d8e18aee1f89c1d1661efc

### Get faculty by name
GET {{url}}/api/faculty/điện ảnh

### Get faculties
GET {{url}}/api/faculties

### Create majors
POST {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors
Content-Type: application/json

{
    "majorName": "Dien tu vip pro 2",
    "managerIdList": ["670ce73281e90dfee50aa1cc"]
}

### Get major by id
GET {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67d92d6e7f6b4a73d814fc4f

### Update major
PATCH {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67d92d6e7f6b4a73d814fc4f
Content-Type: application/json

{
    "isActive": false
}

### Delete major
DELETE {{url}}/api/faculties/67d9ac48409de33ad406b76f/majors/67d9ac5e409de33ad406b77a

### Create cohort
POST {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67daae174b71cf1edf744686/cohorts
Content-Type: application/json

{
    "cohortName": "19"
}

### Get cohort
GET {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67d9226c65f93c2caa907327/cohorts/67d928f979161679648256d4

### Delete cohort
DELETE {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67d9226c65f93c2caa907327/cohorts/67d928f979161679648256d4

### Update cohort
PATCH {{url}}/api/faculties/67d8ea6aa50148be3f5adbbf/majors/67d9226c65f93c2caa907327/cohorts/67d928f979161679648256d4
Content-Type: application/json

{
    "currentLevelYear": 2
}