@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21013481",
    "password": "1111"
}

### Create faculty
POST {{url}}/api/faculties
Content-Type: application/json

{
    "facultyName": "Điện ảnh",
    "managerIdList": [],
    "majorList": []
}

### Get faculties
GET {{url}}/api/faculties

### Get faculty by id
GET {{url}}/api/faculties/65e143d8d5592282126467d8

### Get faculty by name
GET {{url}}/api/faculty/công nghệ thông tin

### Update faculty by id
PATCH {{url}}/api/faculties
Content-Type: application/json

{
   "facultyId": "65d4b6c7145a0ed78a37d7d7",
   "data": {
        "facultyName": "2222a"
   }
}

### Delete faculty by id
DELETE {{url}}/api/faculties/65d6e123530e21efa2dafe6c

### Create majors
POST {{url}}/api/faculties/670ce2e79cfcef01f024c052/majors
Content-Type: application/json

{
    "majorNameList": []
}

### Get major by id
GET {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d6e7a87e72e4352c820b55

### Update major
PATCH {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d4b760145a0ed78a37d803
Content-Type: application/json

{
    "isActive": false
}

### Delete major
DELETE {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d6e7a87e72e4352c820b55

### Create cohort
POST {{url}}/api/faculties/670ce2e79cfcef01f024c052/majors/678364e76edcad8e9c020bda/cohorts
Content-Type: application/json

{
    "cohortName": 18
}

### Get all cohort by id
GET {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d4b760145a0ed78a37d803/cohorts/65d6f1ea525026bb0202a421

### Delete cohort
DELETE {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d4b760145a0ed78a37d803/cohorts/65d6f1ea525026bb0202a421

### Update cohort
PATCH {{url}}/api/faculties/65d4b757145a0ed78a37d800/majors/65d4b760145a0ed78a37d803/cohorts/65d6f1d5525026bb0202a417
Content-Type: application/json

{
    "currentLevelYear": 2
}