@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21013481",
    "password": "1111"
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu", 
    "tables": [
        {
            "tableName": "Nghiên cứu tuyen sinh",
            "description": "Description 1",
            "rowTitleList": [{
                "titleValue": "row 1",
                "fixedValue": []
            }, {
                "titleValue": "row 2",
                "fixedValue": []
            }, {
                "titleValue": "row 3",
                "fixedValue": []
            }, {
                "titleValue": "row 4",
                "fixedValue": []
            }, {
                "titleValue": "row 5",
                "fixedValue": []
            }],
            "rowValueList": [],
            "quantityDemanded": 5,
            "fixedScore": 10
        }
    ],
    "pageType": "chỉ tiêu",
    "pageFaculty": "Công nghệ thông tin",
    "pageStudentCohort": 17,
    "pageStudentMajor": "Kỹ thuật phần mềm",
    "pageStudentLevelYear": 1
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Tin Tức Khoa Học", 
    "pageType": "tin tức"
}

### Create News Page 
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu"
}

### Remove page
DELETE {{url}}/api/page
Content-Type: application/json

{
    "pageId": "654903da5fc9d102a4430fb7"
}
### Get all table
GET {{url}}/api/page 

### Add table
POST {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tables": [
        {
            "tableName": "Hoc Tap V2",
            "description": "La Mo Ta Bang Hoc Tap V2",
            "rowTitleList": ["Ten Mon", "So Tin Chi", "Xep Loai", "Thuc Hanh", "Tinh Trang"],
            "rowValueList": []
        }
    ] 
}

### Remove table
DELETE {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tableId": "6548b5ef623b01bd37769cb2"
}

### Update table
PATCH {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6549076834040537486db1c5",
    "tableData": {
        "tableName": "Hoc Tap Nghien Cuu",
        "rowTitleList": [
            "Ten Mon",
            "So Tin Chi",
            "Xep Loai",
            "Thuc Hanh",
            "Tinh Trang"
        ]
    },
    "tableId": "6549076834040537486db1c6"
}
### Add row
POST {{url}}/api/rows
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="files"; filename="dummy.pdf"
Content-Type: application/pdf

< ./data/dummy.pdf
--MyBoundary
Content-Disposition: form-data; name="rowData"
Content-Type: application/json

{
    "user": "65d98ca4fe939cfae60740f8",
    "table": "65d98f5024ee301790cca8a7", 
    "page": "65d98f5024ee301790cca8a6",
    "content": "{\"row 1\":\"1\",\"row 2\":\"2\",\"row 3\":\"3\",\"row 4\":\"4\",\"row 5\":\"5\"}"
}

--MyBoundary--

### Get pedding row
GET {{url}}/api/pending_rows?limit=3&page=2

### Update status row
PATCH {{url}}/api/dynamic-rows/update
Content-Type: application/json

{
    "status": true,
    "contentIdList": ["654bb94335ed023d2c710209", "654bb94f35ed023d2c710218", "654bba2e35ed023d2c710249"],
    "rowListId": "654bb94335ed023d2c710208"
}

### Get row
GET {{url}}/api/row
Content-Type: application/json

### Get activities
GET {{url}}/api/page/activities?pageStudentMajor=kỹ thuật phần mềm&pageStudentLevelYear=1&pageStudentCohort=17

### Get dynamic rows
GET {{url}}/api/dynamic-rows?page=1&limit=10&current_rows=0&rows_type=acceptedRows&activity=học vượt các môn&pageStudentMajor=kỹ thuật phần mềm&pageStudentLevelYear=1&pageStudentCohort=17
