@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21000696",
    "password": "1111"
}

### Get progress
GET {{url}}/api/progress?pageStudentMajor=Kỹ thuật phần mềm&pageStudentLevelYear=1&pageStudentCohort=17

### Get all student's progress
GET {{url}}/api/progress/all?groupCode=001&faculty=công nghệ thông tin&major=kỹ thuật phần mềm&cohort=20&levelYear=2&sortProgressPercentage=-1

### remove students if they don't pass 
POST {{url}}/api/progress/updated-users
Content-Type: application/json

{
    "cohort": 17,
    "levelYear": 1,
    "major": "kỹ thuật phần mềm",
    "minimunPercentage": 25
}

### Export register form

POST {{url}}/api/progress/register-form
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODY4ZWE2NGNjYWQ3NTllYTU5ZjE2NzEiLCJpYXQiOjE3NTE4NzAyMzIsImV4cCI6MTc1MTg4ODIzMn0.EJ8Bm7E_Yv5Brs83_sYCdcoxgN4SGJrfBVG6DZOkO7Q
