@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21078101",
    "password": "1111"
}

### Add group to user
POST {{url}}/api/users/670ce73281e90dfee50aa1cc/groups/670cdd2e58c8cef6bf3f0df8

### Get users
GET {{url}}/api/users?major=kỹ thuật phần mềm&cohort=20&limit=5&page=1&groupCode=002&sortByName=-1


