const GLOBALTYPES = {
    AUTH: {
        SET_INFO_LOGIN: 'SET_INFO_LOGIN'
    },
    ALERT: 'ALERT',
    PAGE: {
        SET_DYNAMIC_PATH_NAME: 'SET_DYNAMIC_PATH_NAME',
        GET_DYNAMIC_PAGES: 'GET_DYNAMIC_PAGES',
        DYNAMIC_PAGE_INFO: 'DYNAMIC_PAGE_INFO',
        UPDATE_DYNAMIC_PAGE: 'UPDATE_DYNAMIC_PAGE',
        REMOVE_DYNAMIC_PAGE: 'REMOVE_DYNAMIC_PAGE'
    },
    ROW: {
        GET_DYNAMIC_ROWS: 'GET_DYNAMIC_ROWS',
        REMOVE_ALL_ROW: 'REMOVE_ALL_ROW',
        REMOVE_ROW: 'REMOVE_ROW',
        LOADING_PENDING_ROWS: 'LOADING_PENDING_ROWS'
    },
    TABLE: {
        SET_TABLES: 'SET_TABLES'
    },
    NEWS: {
        GET_NEWS: 'GET_NEWS',
        GET_NEWS_DETAILS: 'GET_NEWS_DETAILS',
    },
    PROGRESS: {
        GET_PROGRESS_BY_YEAR: 'GET_PROGRESS_BY_YEAR'
    },
    CHATBOT: {
        ANSWER_CHATBOT_LOADING: 'ANSWER_CHAT_LOADING',
        SET_CHATBOT_DATA: 'SET_CHATBOT_DATA'
    }
};

export default GLOBALTYPES;
