const GLOBALTYPES = {
    AUTH: {
        SET_INFO_LOGIN: 'SET_INFO_LOGIN',
        UPDATE_LEVEL_YEAR: 'UPDATE_LEVEL_YEAR'
    },
    ALERT: 'ALERT',
    PAGE: {
        SET_DYNAMIC_PATH_NAME: 'SET_DYNAMIC_PATH_NAME',
        GET_DYNAMIC_PAGES: 'GET_DYNAMIC_PAGES',
        DYNAMIC_PAGE_INFO: 'DYNAMIC_PAGE_INFO',
        UPDATE_DYNAMIC_PAGE: 'UPDATE_DYNAMIC_PAGE',
        REMOVE_DYNAMIC_PAGE: 'REMOVE_DYNAMIC_PAGE'
    },
    ROW: {
        LOADING_PENDING_ROWS: 'LOADING_PENDING_ROWS',
        GET_DYNAMIC_ROWS: 'GET_DYNAMIC_ROWS',
        UPDATE_ROW: 'UPDATE_ROW',
        REMOVE_ROW: 'REMOVE_ROW',
        REFRESH_TAB: 'REFRESH_TAB',
        RESET_ALL_TAB: 'RESET_ALL_TAB'
    },
    TABLE: {
        SET_TABLES: 'SET_TABLES'
    },
    GOALS: {
        GET_GOAL: 'GET_GOAL',
        GET_GOALS: 'GET_GOALS',
        ADD_NEW_GOAL: 'ADD_NEW_GOAL',
        REMOVE_GOAL: 'REMOVE_GOAL',
        REMOVE_GOALS: 'REMOVE_GOALS',
        UPDATE_STATUS_PAGE: 'UPDATE_STATUS_PAGE',
        RESET_GOALS: 'RESET_GOALS',
        UPDATE_STATUS_TABLE: 'UPDATE_STATUS_TABLE'
    },
    NEWS: {
        GET_NEWS: 'GET_NEWS',
        GET_NEWS_DETAILS: 'GET_NEWS_DETAILS'
    },
    PROGRESS: {
        GET_PROGRESS_BY_YEAR: 'GET_PROGRESS_BY_YEAR',
        GET_ANNUAL_TASK_PROGRESS: 'GET_ANNUAL_TASK_PROGRESS',
        RESET_ANNUAL_TASK_PROGRESS: 'RESET_ANNUAL_TASK_PROGRESS'
    },
    CHATBOT: {
        ANSWER_CHATBOT_LOADING: 'ANSWER_CHAT_LOADING',
        SET_CHATBOT_DATA: 'SET_CHATBOT_DATA',
        GET_TYPE_CHAT: 'GET_TYPE_CHAT'
    },
    SOCKET: {
        SET_SOCKET: 'SET_SOCKET'
    },
    NOTIFICATION: {
        GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
        UPDATE_STATUS_READ_NOTIFICATION: 'UPDATE_STATUS_READ_NOTIFICATION',
        DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
        DELETE_ALL_OTIFICATION: 'DELETE_ALL_OTIFICATION',
        MARK_ALL_AS_READ: 'MARK_ALL_AS_READ',
        LOADING_NOTIFICATIONS: 'LOADING_NOTIFICATIONS',
        GET_NUM_UNREAD_NOTIFICATION: 'GET_NUM_UNREAD_NOTIFICATION',
        ADD_NOTIFICATION: 'ADD_NOTIFICATION'
    },
    FACULTY: {
        GET_ALL_FACULTIES: 'GET_ALL_FACULTIES',
        GET_FACULTY: 'GET_FACULTY',
        ADD_FACULTY: 'ADD_FACULTY',
        UPDATE_FACULTY: 'UPDATE_FACULTY'
    },
    ACTIVITIES: {
        GET_ACTIVITIES: 'GET_ACTIVITIES',
        RESET_ACTIVITIES: 'RESET_ACTIVITIES'
    },
    STUDENT: {
        GET_STUDENTS: 'GET_STUDENTS',
        LOADING: 'LOADING',
        RESET_STUDENT_LIST: 'RESET_STUDENT_LIST',
        UPDATE_STUDENT: 'UPDATE_STUDENT'
    }
};

export default GLOBALTYPES;
