@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "studentId": "21013481",
    "password": "1111"
}


### Create notification v1
POST {{url}}/api/notifications
Content-Type: application/json

{
    "title": "Thông báo về cuộc thi lập trình 2024 và chi tiết giải thưởng",
    "content": "",
    "senderId": "65d4b6bd145a0ed78a37d7d3"
}

### Create notification v2
POST {{url}}/api/notifications
Content-Type: application/json

{
    "title": "Thông báo về cuộc thi lập trình 2024 do nhà trường tổ chức",
    "recipientId": "65d4b6bd145a0ed78a37d7d3",
    "content": "",
    "senderId": "65d4b6bd145a0ed78a37d7d3"
}

### Get notifications
GET {{url}}/api/notifications/65d4b6bd145a0ed78a37d7d3?page=2&limit=5&currentNumNotifications=5

### Update the reading status of the notification
PATCH {{url}}/api/notifications/65d704e9bff7d8ecdaf45ff2/updated-status
Content-Type: application/json

{
    "status": true,
    "recipientId": "65a64bab4d293481a51f9c63"
}

### Delete notification
DELETE {{url}}/api/notifications/65d704e9bff7d8ecdaf45ff2
Content-Type: application/json

{
    "recipientId": "65a64bab4d293481a51f9c63"
}

### Mark read all notification
PATCH {{url}}/api/notifications/updated-status
Content-Type: application/json

{
    "recipientId": "65a64bab4d293481a51f9c63"
}

### Delete all notification
DELETE  {{url}}/api/notifications
Content-Type: application/json

{
    "recipientId": "65a64bab4d293481a51f9c63"
}

### Get the number of unread notifications
GET {{url}}/api/notifications/65d4b6bd145a0ed78a37d7d3/unread-notifications
