@url=http://localhost:4000

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "userId": "21013481",
    "password": "1111"
}

### Get progress
GET {{url}}/api/progress?pageStudentMajor=Kỹ thuật phần mềm&pageStudentLevelYear=1&pageStudentCohort=17

### Get all student's progress
GET {{url}}/api/progress/all?major=kỹ thuật phần mềm&cohort=17&levelYear=1&isCompleted=false

### remove students if they don't pass 
POST {{url}}/api/progress/updated-users
Content-Type: application/json

{
    "cohort": 17,
    "levelYear": 1,
    "major": "kỹ thuật phần mềm",
    "minimunPercentage": 25
}


