@url=http://localhost:4000

###
GET {{url}}

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "studentId": "21013481",
    "password": "1111"
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu", 
    "pageType": "chỉ tiêu",
    "tables": [
        {
            "tableName": "Nghiên cứu tuyen sinh",
            "description": "Description 1",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động sinh tuyen",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động tuyen tuyen",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động sinh sinh 2",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        }
    ] 
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Tin Tức Khoa Học", 
    "pageType": "tin tức"
}

### Create News Page 
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu"
}

### Get all table
GET {{url}}/api/page

### remove page
DELETE {{url}}/api/page
Content-Type: application/json

{
    "pageId": "654903da5fc9d102a4430fb7"
}

### Add table
POST {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tables": [
        {
            "tableName": "Hoc Tap V2",
            "description": "La Mo Ta Bang Hoc Tap V2",
            "rowTitleList": ["Ten Mon", "So Tin Chi", "Xep Loai", "Thuc Hanh", "Tinh Trang"],
            "rowValueList": []
        }
    ] 
}

### Remove table
DELETE {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tableId": "6548b5ef623b01bd37769cb2"
}

### Update table
PATCH {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6549076834040537486db1c5",
    "tableData": {
        "tableName": "Hoc Tap Nghien Cuu",
        "rowTitleList": [
            "Ten Mon",
            "So Tin Chi",
            "Xep Loai",
            "Thuc Hanh",
            "Tinh Trang"
        ]
    },
    "tableId": "6549076834040537486db1c6"
}
### add row
POST {{url}}/api/row
Content-Type: application/json

{   
    "page": "65570d108e800ae7c5adeace",
    "user": "65570c9b8e800ae7c5adeac7",
    "table": "65570d108e800ae7c5adeacf"
}
### get pedding row
GET {{url}}/api/pending_rows?limit=3&page=2

### update status row
PATCH {{url}}/api/dynamic_rows/update
Content-Type: application/json

{
    "status": true,
    "contentIdList": ["654bb94335ed023d2c710209", "654bb94f35ed023d2c710218", "654bba2e35ed023d2c710249"],
    "rowListId": "654bb94335ed023d2c710208"
}

###
GET {{url}}/api/row
Content-Type: application/json

###
POST {{url}}/api/register 
Content-Type: application/json

{
    "studentId": "2100123",
    "fullName": "nguyen123",
    "birthday": "19-05-2003",
    "major": "CNTT",
    "password": "1111",
    "email": "n4g2u12312",
    "phone": "0943608225"
}

###
GET {{url}}/api/access_token

### Get Posts
GET {{url}}/api/news?news_type=Tin%20Tức%20Đào%20Tạo

### Create Post
POST {{url}}/api/post
Content-Type: application/json

{
    "title": "ga di bo",
    "content": "ga khong di bo"
}

###
PATCH  {{url}}/api/post
Content-Type: application/json

{
    "id": "654503788fafe8b70e49202a",
    "title": "ga tap lai xe",
    "content": "ga truot lai xe"
}

###
DELETE  {{url}}/api/post
Content-Type: application/json

{
    "id": "654508a14e88b334461830f7"
}

### Get Faculties
GET {{url}}/api/faculty

### Get Majors
GET {{url}}/api/faculty/65562daecfe9a2f7336e53ce


### Create Faculty
POST {{url}}/api/faculty
Content-Type: application/json

{
    "facultyName": "Điện tử máy tính",
    "isActive": true,
    "majors": [
        {
            "majorName": "Kỹ thuật điện tử",
            "isActive": true
        },
        {
            "majorName": "Hệ thống mạch dẫn",
            "isActive": false
        }
    ]
}

### Update Faculty
PATCH  {{url}}/api/faculty
Content-Type: application/json

{
    "facultyId": "65562daecfe9a2f7336e53ce",
    "facultyName": "Công nghệ thông tin",
    "isActive": false,
    "majors": [
        {
            "majorName": "Kỹ thuật phần mềm",
            "isActive": true
        },
        {
            "majorName": "Khoa học máy tính",
            "isActive": true
        }
    ]
}

###
DELETE {{url}}/api/faculty
Content-Type: application/json

{
    "facultyId": "655625fc62e1cd4fa44e4ff7"
}

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "studentId": "21013481",
    "password": "1111"
}

### get progress
GET {{url}}/api/progress?pageStudentMajor=Kỹ thuật phần mềm&pageStudentLevelYear=1&pageStudentCohort=17

### get all student's progress
GET {{url}}/api/progress/all?major=kỹ thuật phần mềm&cohort=17&levelYear=1&isCompleted=false

### remove students if they don't pass 
POST {{url}}/api/progress/updatedUsers
Content-Type: application/json

{
    "cohort": 17,
    "levelYear": 1,
    "major": "kỹ thuật phần mềm",
    "minimunPercentage": 25
}