@url=http://localhost:4000

###
GET {{url}}

### Login
POST {{url}}/api/login
Content-Type: application/json

{
    "studentId": "21013481",
    "password": "1111"
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu", 
    "pageType": "Chỉ Tiêu",
    "tables": [
        {
            "tableName": "Nghiên cứu tuyen sinh",
            "description": "Description 1",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động sinh tuyen",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động tuyen tuyen",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        },
        {
            "tableName": "Hoạt động sinh sinh 2",
            "description": "Description 3",
            "rowTitleList": ["row 1", "row 2", "row 3", "row 4", "row 5"],
            "rowValueList": []
        }
    ] 
}

### Create Page and mutiple tables
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Tin Tức Khoa Học", 
    "pageType": "Tin Tức"
}

### Create News Page 
POST {{url}}/api/page
Content-Type: application/json

{
    "pageName": "Hoạt động Nghien Cuu"
}

### Get all table
GET {{url}}/api/page

### remove page
DELETE {{url}}/api/page
Content-Type: application/json

{
    "pageId": "654903da5fc9d102a4430fb7"
}

### Add table
POST {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tables": [
        {
            "tableName": "Hoc Tap V2",
            "description": "La Mo Ta Bang Hoc Tap V2",
            "rowTitleList": ["Ten Mon", "So Tin Chi", "Xep Loai", "Thuc Hanh", "Tinh Trang"],
            "rowValueList": []
        }
    ] 
}

### Remove table
DELETE {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6548965e36bbd99ed5fffffd",
    "tableId": "6548b5ef623b01bd37769cb2"
}

### Update table
PATCH {{url}}/api/table
Content-Type: application/json

{
    "pageId": "6549076834040537486db1c5",
    "tableData": {
        "tableName": "Hoc Tap Nghien Cuu",
        "rowTitleList": [
            "Ten Mon",
            "So Tin Chi",
            "Xep Loai",
            "Thuc Hanh",
            "Tinh Trang"
        ]
    },
    "tableId": "6549076834040537486db1c6"
}
###
POST {{url}}/api/row
Content-Type: application/json

{   
    "page": "6539da65395099f799f4d312",
    "user": "6537f6c1adc22ad3e1829e21",
    "table": "6547b4af4f0a7fc174b69cc0",
    "content": ["content 1", "content 2", "content 3", "content 4", "content 5"]
}

### update status row
PATCH {{url}}/api/pending_rows/update
Content-Type: application/json

{
    "status": true,
    "contentIdList": ["654bb94335ed023d2c710209", "654bb94f35ed023d2c710218", "654bba2e35ed023d2c710249"],
    "rowListId": "654bb94335ed023d2c710208"
}

###
GET {{url}}/api/row
Content-Type: application/json

###
POST {{url}}/api/register 
Content-Type: application/json

{
    "studentId": "2100123",
    "fullName": "nguyen123",
    "birthday": "19-05-2003",
    "major": "CNTT",
    "password": "1111",
    "email": "n4g2u12312",
    "phone": "0943608225"
}

###
GET {{url}}/api/access_token

### Get Posts
GET {{url}}/api/news?news_type=Tin%20Tức%20Đào%20Tạo

### Get Post
GET {{url}}/api/post/654503788fafe8b70e49202a

### Create Post
POST {{url}}/api/post
Content-Type: application/json

{
    "title": "ga di bo",
    "content": "ga khong di bo"
}

###
PATCH  {{url}}/api/post
Content-Type: application/json

{
    "id": "654503788fafe8b70e49202a",
    "title": "ga tap lai xe",
    "content": "ga truot lai xe"
}

###
DELETE  {{url}}/api/post
Content-Type: application/json

{
    "id": "654508a14e88b334461830f7"
}